version: '3.9'
services:
  new-relic-exporter:
    platform: linux/amd64
    environment:
      - VERSION=$VERSION
    build:
      context: ./
    image: ghcr.io/newrelic-experimental/gha-new-relic-exporter:$VERSION
